2025-09-22 00:17:32,191 - network_analyzer.main - INFO - 启动网络流量统计系统...
2025-09-22 00:17:32,191 - network_analyzer.main - INFO - 版本: 0.1.0
2025-09-22 00:17:32,196 - network_analyzer.main - ERROR - 需要管理员权限才能捕获网络数据包
2025-09-22 00:33:26,661 - network_analyzer.main - INFO - 启动网络流量统计系统...
2025-09-22 00:33:26,662 - network_analyzer.main - INFO - 版本: 0.1.0
2025-09-22 00:33:26,666 - root - ERROR - 程序运行出错: 'Settings' object has no attribute 'DATA_DIRECTORY'
Traceback (most recent call last):
  File "D:\项目\计算机网络课设\LightweightPacketAnalyzer\src\network_analyzer\main.py", line 87, in main
    data_dir = Path(settings.DATA_DIRECTORY)
                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'DATA_DIRECTORY'
2025-09-22 14:05:54,311 - network_analyzer.main - INFO - 启动网络流量统计系统...
2025-09-22 14:05:54,311 - network_analyzer.main - INFO - 版本: 0.1.0
2025-09-22 14:05:54,317 - network_analyzer.main - INFO - 启动图形界面...
2025-09-22 14:05:54,323 - network_analyzer.storage.data_manager - INFO - 数据库初始化完成
2025-09-22 14:05:54,492 - network_analyzer.gui.main_window - INFO - 主窗口初始化完成
2025-09-22 14:06:27,445 - network_analyzer.gui.main_window - INFO - 开始数据包捕获
2025-09-22 14:06:41,966 - network_analyzer.gui.main_window - INFO - 停止数据包捕获
2025-09-22 14:07:31,377 - network_analyzer.gui.main_window - INFO - 开始数据包捕获
2025-09-22 14:09:37,378 - network_analyzer.gui.main_window - INFO - 用户关闭应用程序
2025-09-22 14:16:24,945 - network_analyzer.main - INFO - 启动网络流量统计系统...
2025-09-22 14:16:24,945 - network_analyzer.main - INFO - 版本: 0.1.0
2025-09-22 14:16:24,950 - network_analyzer.main - INFO - 启动图形界面...
2025-09-22 14:16:24,952 - network_analyzer.storage.data_manager - INFO - 数据库初始化完成
2025-09-22 14:16:25,037 - network_analyzer.gui.main_window - INFO - 主窗口初始化完成
2025-09-22 14:16:27,332 - network_analyzer.gui.main_window - INFO - 开始数据包捕获
2025-09-22 14:16:31,012 - network_analyzer.gui.main_window - INFO - 停止数据包捕获
2025-09-22 14:16:38,332 - network_analyzer.gui.main_window - INFO - 用户关闭应用程序
